#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.20f1_6dd1c08eedfa"
#define UNITY_VERSION_FULL_NICE "2019.4.20f1 (6dd1c08eedfa)"
#define UNITY_VERSION_BLD 7197120
#define UNITY_VERSION_DATE 1612467025
#define UNITY_VERSION_WIN "2019.4.20.7197120"
#define UNITY_VERSION_BRANCH "2019.4/release"
